{{- $ref := dict "root" . "name" "device-simulator" "component" "simulator" -}}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: device-simulator
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: device-simulator:latest
  source:
    contextDir: digital-twin/simulation/device
    git:
      ref: main
      uri: https://github.com/drogue-iot/burrboard
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: ENDPOINT_URL
          value: {{ .Values.simulator.mqttEndpointUrl | quote }}

  triggers:
    - type: ConfigChange
