{{- $ref := dict "root" . "name" "device-simulator" "component" "simulator" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: device-simulator
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"device-simulator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app\")].image"}]'
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "burrboard.selectorLabels" $ref | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{ include "burrboard.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: app
          image: device-simulator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              scheme: HTTP
              path: /
          readinessProbe:
            httpGet:
              port: http
              scheme: HTTP
              path: /
