{{- $ref := dict "root" . "name" "device-simulator" "component" "simulator" -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: device-simulator
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: device-simulator
