kind: Deployment
apiVersion: apps/v1
metadata:
  name: timescaledb-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb-pusher
  template:
    metadata:
      labels:
        app: timescaledb-pusher
    spec:
      containers:
        - name: timescaledb-pusher
          image: {{ .Values.tsdb.pusher.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: RUST_LOG
              value: debug
            - name: RUST_BACKTRACE
              value: "1"

            - name: ACTIX__BIND_ADDR
              value: 0.0.0.0:8080

            - name: POSTGRESQL__CONNECTION__HOST
              value: {{ include "burrboard.timescaledb.host" . }}
            - name: POSTGRESQL__CONNECTION__PORT
              value: {{ include "burrboard.timescaledb.port" . }}
            - name: POSTGRESQL__CONNECTION__DBNAME
              value: {{ .Values.tsdb.timescale.database | quote  }}
            - name: POSTGRESQL__CONNECTION__USER
              value: {{ .Values.tsdb.timescale.writer.username | quote }}
            - name: POSTGRESQL__CONNECTION__PASSWORD
              value: {{ .Values.tsdb.timescale.writer.password | quote }}

            - name: POSTGRESQL__TIME_COLUMN
              value: time

            - name: POSTGRESQL__TABLE
              value: {{ .Values.tsdb.pusher.table | quote }}

            - name: FIELD_TEMPERATURE
              value: $.features.temperature.value
            - name: TYPE_FIELD_TEMPERATURE
              value: float

            - name: FIELD_LIGHT
              value: $.features.light.value
            - name: TYPE_FIELD_LIGHT
              value: float

            - name: FIELD_BUTTON_A
              value: $.features.button_a.presses
            - name: TYPE_BUTTON_A
              value: int

            - name: FIELD_BUTTON_B
              value: $.features.button_b.presses
            - name: TYPE_BUTTON_B
              value: int

            - name: FIELD_ACCELEROMETER_X
              value: $.features.accelerometer.x
            - name: TYPE_FIELD_ACCELEROMETER_X
              value: float
            - name: FIELD_ACCELEROMETER_Y
              value: $.features.accelerometer.y
            - name: TYPE_FIELD_ACCELEROMETER_Y
              value: float
            - name: FIELD_ACCELEROMETER_Z
              value: $.features.accelerometer.z
            - name: TYPE_FIELD_ACCELEROMETER_Z
              value: float

            - name: FIELD_BATTERY
              value: $.features.device.battery
            - name: TYPE_FIELD_BATTERY
              value: float

            # from the headers
            - name: TAG_DEVICE_ID
              value: $.device
