kind: Deployment
apiVersion: apps/v1
metadata:
  name: drogue-event-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drogue-event-source
  template:
    metadata:
      labels:
        app: drogue-event-source
    spec:
      containers:
        - name: drogue-event-source
          image: {{ .Values.tsdb.pusher.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: debug
            - name: RUST_BACKTRACE
              value: "1"

            - name: K_SINK
              value: http://timescaledb-pusher:80
            - name: DROGUE_ENDPOINT
              value: {{ .Values.tsdb.drogueCloud.websocketIntegration.endpoint }}
            - name: DROGUE_APP
              value: {{ .Values.tsdb.drogueCloud.application }}
            - name: DROGUE_USER
              value: {{ .Values.tsdb.drogueCloud.websocketIntegration.user }}
            - name: DROGUE_TOKEN
              value: {{ .Values.tsdb.drogueCloud.websocketIntegration.token }}
