{
 "title": "summit",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Burrboards devices seen",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_burrboard_devices" }
   ]
  },
  {
   "title": "Total burrboard events processed by drogue cloud",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "burrboard_temperature_count" }
   ]
  },
  {
   "title": "Average system latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(burrboard_event_delta_sum/burrboard_event_delta_count)*1000"
    }
   ]
  },
  {
   "title": "Buttons Hits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "A",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "burrboard_buttons_a_presses" }
   ]
  },
  {
   "title": "B",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "burrboard_buttons_b_presses" }
   ]
  },
  {
   "title": "Last 30 seconds (both buttons combined)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(burrboard_buttons_a_presses + burrboard_buttons_b_presses )"
    }
   ]
  },
  { "title": "Light", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Light Average value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burrboard_light_sum/burrboard_light_count"
    },
    {
     "expr": "burrboard_light_sum/burrboard_light_count"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Temperature Average value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "burrboard_temperature_sum/burrboard_temperature_count"
    },
    {
     "expr": "burrboard_temperature_sum/burrboard_temperature_count"
    }
   ]
  }
 ]
}