{{- $ref := dict "root" . "name" "doppelgaenger-websocket" "component" "doppelgaenger" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doppelgaenger-websocket
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"doppelgaenger-websocket:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app\")].image"}]'
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "burrboard.selectorLabels" $ref | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "burrboard.labels" $ref | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
        - name: app
          image: doppelgaenger-websocket
          imagePullPolicy: Always
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  #name: twindb-mongodb
                  #key: mongodb-passwords
                  name: doppelgaegner-config
                  key: mongodb.password
            - name: MONGODB__URL
              #value: mongodb://twin:$(PASSWORD)@twindb-mongodb-headless:27017/
              value: mongodb+srv://drogue-iot:$(PASSWORD)@cluster0.kxq4o.mongodb.net/twin-db?retryWrites=true&w=majority
            - name: DATABASE
              value: twin-db
            - name: DROGUE_APP
              value: burrboard
          ports:
            - containerPort: 8082
              name: web
          livenessProbe:
            httpGet:
              port: 8082
              path: /health
          readinessProbe:
            httpGet:
              port: 8082
              path: /health
