{{- $ref := dict "root" . "name" "doppelgaenger-websocket" "component" "doppelgaenger" -}}
kind: Service
apiVersion: v1
metadata:
  name: doppelgaenger-websocket
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8082
      targetPort: web
  selector:
    {{ include "burrboard.selectorLabels" $ref | nindent 4 }}
