{{- if .Values.tsdb.timescale.deployment.enabled }}
{{- $ref := dict "root" . "name" "post-install-timescaledb" "component" "database" -}}
kind: Job
apiVersion: batch/v1
metadata:
  name: post-install-timescaledb
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1

  template:
    metadata:
      labels:
        {{- include "burrboard.labels" $ref | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.tsdb.timescale.deployment.postInstallImage }}
          env:
            - name:  PGUSER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: admin.username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: admin.password
            - name:  PGDATABASE
              value: {{ .Values.tsdb.timescale.database | quote }}
          command:
            - psql
            - -h
            - timescaledb
            - -c
            - |
              DO $$$$
              BEGIN
              CREATE USER {{ .Values.tsdb.timescale.reader.username }};
              EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
              END
              $$$$;
              ALTER USER {{ .Values.tsdb.timescale.reader.username }} WITH PASSWORD '{{ .Values.tsdb.timescale.reader.password }}';
              GRANT SELECT ON ALL TABLES IN SCHEMA public TO {{ .Values.tsdb.timescale.reader.username }};

              DO $$$$
              BEGIN
              CREATE USER {{ .Values.tsdb.timescale.writer.username }};
              EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
              END
              $$$$;
              ALTER USER {{ .Values.tsdb.timescale.writer.username }} WITH PASSWORD '{{ .Values.tsdb.timescale.writer.password }}';
              GRANT INSERT ON ALL TABLES IN SCHEMA public TO {{ .Values.tsdb.timescale.writer.username }};
{{- end }}