{{- if .Values.tsdb.timescale.deployment.enabled }}
{{- $ref := dict "root" . "name" "timescaledb" "component" "tsdb" -}}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: timescaledb
  labels:
    {{- include "burrboard.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  serviceName: timescaledb
  selector:
    matchLabels:
      {{- include "burrboard.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "burrboard.labels" $ref | nindent 8 }}
    spec:
      initContainers:
        # we need this to gather the existing init script from timescale db and ours
        # into a complete set up of init scripts
        - name: gather-init-scripts
          image: {{ .Values.tsdb.timescale.deployment.image }}
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              cp -v /docker-entrypoint-initdb.d/* /var/lib/docker-entrypoint-initdb.d
              cp -v /etc/docker-entrypoint-initdb.d/* /var/lib/docker-entrypoint-initdb.d
          volumeMounts:
            - mountPath: /etc/docker-entrypoint-initdb.d
              name: initdb-config
            - mountPath: /var/lib/docker-entrypoint-initdb.d
              name: initdb
              readOnly: false
      containers:
        - name: timescaledb
          image: {{ .Values.tsdb.timescale.deployment.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.tsdb.timescale.deployment.admin.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.tsdb.timescale.deployment.admin.password }}
            - name: POSTGRES_DB
              value: {{ .Values.tsdb.timescale.database }}
            - name: PGDATA
              value: /var/lib/storage/pgdata
          volumeMounts:
            - mountPath: /var/lib/storage
              name: storage
              subPath: pgdata
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
            - mountPath: /var/run/postgresql
              name: run-postgres
      volumes:
        - name: initdb
          emptyDir: {}
        - name: run-postgres
          emptyDir: {}
        - name: initdb-config
          configMap:
            name: timescaledb-initdb
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

{{- end }}