kind: Secret
apiVersion: v1
metadata:
  name: timescaledb-secret
data:
  {{- if .Values.tsdb.timescale.deployment.enabled }}
  admin.username: {{ .Values.tsdb.timescale.deployment.admin.username | b64enc | quote }}
  admin.password: {{ .Values.tsdb.timescale.deployment.admin.password | b64enc | quote }}
  {{- end }}
  reader.username: {{ .Values.tsdb.timescale.reader.username | b64enc | quote }}
  reader.password: {{ .Values.tsdb.timescale.reader.password | b64enc | quote }}
  write.username: {{ .Values.tsdb.timescale.writer.username | b64enc | quote }}
  write.password: {{ .Values.tsdb.timescale.writer.password | b64enc | quote }}
