kind: Secret
apiVersion: v1
metadata:
  name: timescaledb-secret
data:
  reader.username: {{ .Values.tsdb.timescale.reader.username | b64enc | quote }}
  reader.password: {{ .Values.tsdb.timescale.reader.password | b64enc | quote }}
  write.username: {{ .Values.tsdb.timescale.writer.username | b64enc | quote }}
  write.password: {{ .Values.tsdb.timescale.writer.password | b64enc | quote }}
