kafka:
  bootstrapServer: ""
  topic: ""
  username: ""
  password: ""

mongoDb:
  database: twin-db
  url: ""

drogueCloud:
  application: ""

simulatorUrl: ""

simulator:
  mqttEndpointUrl: ""

tsdb:
  drogueCloud:
    application: burrboard
    websocketIntegration:
      endpoint: ""
      user: ""
      token: ""

  pusher:
    image: "ghcr.io/drogue-iot/postgresql-pusher:0.1.0"
    table: devices

  grafana:
    adminPassword: ""
    image: "docker.io/grafana/grafana:8.4.2"

  timescale:
    host: ""
    port: 5432
    database: "tsdb"
    reader:
      username: ""
      password: ""
    writer:
      username: ""
      password: ""
